In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv("../data/raw/electronics_reviews.csv")

In [3]:
product_name = (
    "Logitech 915-000224  Harmony Ultimate One "
    "15-Device Universal Infrared Remote with "
    "Customizable Touch Screen Control - Black"
)

product_df = df[
    df["name"] == product_name
].copy()

In [4]:
product_df.shape

(1604, 27)

In [5]:
product_df["original_text"] = product_df["reviews.text"]

In [6]:
product_df[
    ["original_text", "reviews.rating"]
].head()

                                          original_text  reviews.rating
5691  Cannot hit play, FF or Rev, etc, without havin...             1.0
5692  HAHAHAHAHA! I'm the master of my own universe ...             5.0
5693  I bought this remote to replace my Harmony 650...             5.0
5694                 Universal remote control excellent             5.0
5695  Other than a few oddly placed buttons, I could...             4.0

In [ ]:
#Clean text
product_df["cleaned_text"] = product_df["original_text"]

In [ ]:
#lower text
product_df["cleaned_text"] = product_df["cleaned_text"].str.lower()

In [21]:
product_df[
    ["original_text", "cleaned_text"]
].head(10)

,original_text,cleaned_text
5691,"Cannot hit play, FF or Rev, etc, without havin...","cannot hit play, ff or rev, etc, without havin..."
5692,HAHAHAHAHA! I'm the master of my own universe ...,hahahahaha! i'm the master of my own universe ...
5693,I bought this remote to replace my Harmony 650...,i bought this remote to replace my harmony 650...
5694,Universal remote control excellent,universal remote control excellent
5695,"Other than a few oddly placed buttons, I could...","other than a few oddly placed buttons, i could..."
5696,difficult to use,difficult to use
5697,Do what it's supposed to do. Reaction time of ...,do what it's supposed to do. reaction time of ...
5698,Works great,works great
5699,This Ultimate One is a great improvement over ...,this ultimate one is a great improvement over ...
5700,Thought this was similar to my previous Logite...,thought this was similar to my previous logite...

In [22]:
##Remove URLs

product_df["cleaned_text"] = product_df["cleaned_text"].apply(
    lambda text: re.sub(r"http\S+|www\S+", "", text)
)

In [23]:
product_df[
    ["original_text", "cleaned_text"]
].sample(5, random_state=42)

,original_text,cleaned_text
6221,This is the worst remote we have ever had. The...,this is the worst remote we have ever had. the...
6831,I'm having trouble turning my Wii game system ...,i'm having trouble turning my wii game system ...
5859,My Harmony 900 died and I needed a replacement...,my harmony 900 died and i needed a replacement...
5826,Are they there yet Nope. Still a pretty big a ...,are they there yet nope. still a pretty big a ...
6129,Good book but limited in scope!,good book but limited in scope!

In [ ]:
## punctuation with whitespace

product_df["cleaned_text"] = product_df["cleaned_text"].apply(
    lambda text: re.sub(r"[^\w\s']", " ", text)
)

In [ ]:
##Normalize whitespace
product_df["cleaned_text"] = product_df["cleaned_text"].apply(
    lambda text: re.sub(r"\s+", " ", text).strip()
)

In [26]:
product_df.loc[
    6174,
    ["original_text", "cleaned_text"]
]

original_text    Everyone in my family got tired of having 4-5 ...
cleaned_text     everyone in my family got tired of having 4 5 ...
Name: 6174, dtype: str

In [27]:
product_df.loc[
    6831,
    ["original_text", "cleaned_text"]
]

original_text    I'm having trouble turning my Wii game system ...
cleaned_text     i'm having trouble turning my wii game system ...
Name: 6831, dtype: str

In [28]:
product_df[
    ["original_text", "cleaned_text"]
].sample(10, random_state=42)

,original_text,cleaned_text
6221,This is the worst remote we have ever had. The...,this is the worst remote we have ever had the ...
6831,I'm having trouble turning my Wii game system ...,i'm having trouble turning my wii game system ...
5859,My Harmony 900 died and I needed a replacement...,my harmony 900 died and i needed a replacement...
5826,Are they there yet Nope. Still a pretty big a ...,are they there yet nope still a pretty big a b...
6129,Good book but limited in scope!,good book but limited in scope
7183,This remote does it all and even corrects my m...,this remote does it all and even corrects my m...
6995,I love the fact I can use one remote to turn e...,i love the fact i can use one remote to turn e...
5930,I owned 2 Harmony One and this is my 3rd Logit...,i owned 2 harmony one and this is my 3rd logit...
6174,Everyone in my family got tired of having 4-5 ...,everyone in my family got tired of having 4 5 ...
5991,I looked at this remote 2 days ago and decided...,i looked at this remote 2 days ago and decided...

In [29]:
product_df[
    ["original_text", "cleaned_text"]
].sample(10, random_state=42)

,original_text,cleaned_text
6221,This is the worst remote we have ever had. The...,this is the worst remote we have ever had the ...
6831,I'm having trouble turning my Wii game system ...,i'm having trouble turning my wii game system ...
5859,My Harmony 900 died and I needed a replacement...,my harmony 900 died and i needed a replacement...
5826,Are they there yet Nope. Still a pretty big a ...,are they there yet nope still a pretty big a b...
6129,Good book but limited in scope!,good book but limited in scope
7183,This remote does it all and even corrects my m...,this remote does it all and even corrects my m...
6995,I love the fact I can use one remote to turn e...,i love the fact i can use one remote to turn e...
5930,I owned 2 Harmony One and this is my 3rd Logit...,i owned 2 harmony one and this is my 3rd logit...
6174,Everyone in my family got tired of having 4-5 ...,everyone in my family got tired of having 4 5 ...
5991,I looked at this remote 2 days ago and decided...,i looked at this remote 2 days ago and decided...

In [30]:
(product_df["cleaned_text"].str.strip() == "").sum()

np.int64(0)

In [31]:
#review length

product_df["cleaned_length"] = (
    product_df["cleaned_text"]
    .str.split()
    .str.len()
)

In [32]:
product_df["cleaned_length"].describe()

count    1604.000000
mean       70.146509
std       121.470699
min         1.000000
25%        17.000000
50%        33.000000
75%        71.250000
max      1756.000000
Name: cleaned_length, dtype: float64

In [33]:
output_path = "../data/processed/harmony_reviews_cleaned.csv"

product_df.to_csv(
    output_path,
    index=False
)

print(f"Saved to: {output_path}")

Saved to: ../data/processed/harmony_reviews_cleaned.csv